// -----------------------------------------------------------------------------
// This file was autogenerated by symforce from template:
//     function/FUNCTION.h.jinja
// Do NOT modify by hand.
// -----------------------------------------------------------------------------

#pragma once

#include <sym/pose3.h>

#include <Eigen/Dense>

namespace sym {

/**
 * This function was autogenerated from a symbolic function. Do not modify by
 * hand.
 *
 * Symbolic function: reprojectionResidual
 *
 * Args:
 *     robot_ax_ang: Matrix31
 *     robot_transl: Matrix31
 *     landmark: Matrix31
 *     extrinsics: Pose3
 *     obs: Matrix21
 *     pixel_err_mult_x: Scalar
 *     pixel_err_mult_y: Scalar
 *     epsilon: Scalar
 *
 * Outputs:
 *     res: Matrix21
 *     res_D_robot_ax_ang: (2x3) jacobian of res (2) wrt arg robot_ax_ang (3)
 *     res_D_robot_transl: (2x3) jacobian of res (2) wrt arg robot_transl (3)
 *     res_D_landmark: (2x3) jacobian of res (2) wrt arg landmark (3)
 */
template <typename Scalar>
Eigen::Matrix<Scalar, 2, 1> ReprojectionresidualWithJacobians012(
    const Eigen::Matrix<Scalar, 3, 1>& robot_ax_ang,
    const Eigen::Matrix<Scalar, 3, 1>& robot_transl,
    const Eigen::Matrix<Scalar, 3, 1>& landmark,
    const sym::Pose3<Scalar>& extrinsics,
    const Eigen::Matrix<Scalar, 2, 1>& obs,
    const Scalar pixel_err_mult_x,
    const Scalar pixel_err_mult_y,
    const Scalar epsilon,
    Eigen::Matrix<Scalar, 2, 3>* const res_D_robot_ax_ang = nullptr,
    Eigen::Matrix<Scalar, 2, 3>* const res_D_robot_transl = nullptr,
    Eigen::Matrix<Scalar, 2, 3>* const res_D_landmark = nullptr) {
  // Total ops: 866

  // Input arrays
  const Eigen::Matrix<Scalar, 7, 1>& _extrinsics = extrinsics.Data();

  // Intermediate terms (294)
  const Scalar _tmp0 = std::pow(robot_ax_ang(2, 0), Scalar(2));
  const Scalar _tmp1 = std::pow(robot_ax_ang(0, 0), Scalar(2));
  const Scalar _tmp2 = std::pow(robot_ax_ang(1, 0), Scalar(2));
  const Scalar _tmp3 = _tmp0 + _tmp1 + _tmp2 + epsilon;
  const Scalar _tmp4 = std::sqrt(_tmp3);
  const Scalar _tmp5 = (Scalar(1) / Scalar(2)) * _tmp4;
  const Scalar _tmp6 = std::sin(_tmp5);
  const Scalar _tmp7 = _tmp6 / _tmp4;
  const Scalar _tmp8 = _extrinsics[1] * _tmp7;
  const Scalar _tmp9 = _tmp8 * robot_ax_ang(0, 0);
  const Scalar _tmp10 = _extrinsics[3] * _tmp7;
  const Scalar _tmp11 = _tmp10 * robot_ax_ang(2, 0);
  const Scalar _tmp12 = _extrinsics[0] * _tmp7;
  const Scalar _tmp13 = _tmp12 * robot_ax_ang(1, 0);
  const Scalar _tmp14 = std::cos(_tmp5);
  const Scalar _tmp15 = _extrinsics[2] * _tmp14;
  const Scalar _tmp16 = _tmp11 - _tmp13 + _tmp15 + _tmp9;
  const Scalar _tmp17 = _tmp8 * robot_ax_ang(1, 0);
  const Scalar _tmp18 = _tmp12 * robot_ax_ang(0, 0);
  const Scalar _tmp19 = _extrinsics[2] * _tmp7;
  const Scalar _tmp20 = _tmp19 * robot_ax_ang(2, 0);
  const Scalar _tmp21 = _extrinsics[3] * _tmp14;
  const Scalar _tmp22 = -_tmp17 - _tmp18 - _tmp20 + _tmp21;
  const Scalar _tmp23 = 2 * _tmp22;
  const Scalar _tmp24 = _tmp16 * _tmp23;
  const Scalar _tmp25 = _tmp8 * robot_ax_ang(2, 0);
  const Scalar _tmp26 = _tmp10 * robot_ax_ang(0, 0);
  const Scalar _tmp27 = _tmp19 * robot_ax_ang(1, 0);
  const Scalar _tmp28 = _extrinsics[0] * _tmp14;
  const Scalar _tmp29 = -_tmp25 + _tmp26 + _tmp27 + _tmp28;
  const Scalar _tmp30 = _tmp10 * robot_ax_ang(1, 0);
  const Scalar _tmp31 = _tmp12 * robot_ax_ang(2, 0);
  const Scalar _tmp32 = _tmp19 * robot_ax_ang(0, 0);
  const Scalar _tmp33 = _extrinsics[1] * _tmp14;
  const Scalar _tmp34 = _tmp30 + _tmp31 - _tmp32 + _tmp33;
  const Scalar _tmp35 = 2 * _tmp34;
  const Scalar _tmp36 = _tmp29 * _tmp35;
  const Scalar _tmp37 = _tmp24 + _tmp36;
  const Scalar _tmp38 = _tmp22 * _tmp35;
  const Scalar _tmp39 = -_tmp38;
  const Scalar _tmp40 = 2 * _tmp16;
  const Scalar _tmp41 = _tmp29 * _tmp40;
  const Scalar _tmp42 = _tmp39 + _tmp41;
  const Scalar _tmp43 = 2 * std::pow(_tmp16, Scalar(2));
  const Scalar _tmp44 = -_tmp43;
  const Scalar _tmp45 = 2 * std::pow(_tmp34, Scalar(2));
  const Scalar _tmp46 = 1 - _tmp45;
  const Scalar _tmp47 = _tmp44 + _tmp46;
  const Scalar _tmp48 = std::pow(_tmp6, Scalar(2));
  const Scalar _tmp49 = Scalar(1.0) / (_tmp3);
  const Scalar _tmp50 = _tmp48 * _tmp49;
  const Scalar _tmp51 = _tmp50 * robot_ax_ang(1, 0);
  const Scalar _tmp52 = _tmp51 * robot_ax_ang(0, 0);
  const Scalar _tmp53 = 2 * _tmp52;
  const Scalar _tmp54 = 2 * _tmp14;
  const Scalar _tmp55 = _tmp54 * _tmp7;
  const Scalar _tmp56 = _tmp55 * robot_ax_ang(2, 0);
  const Scalar _tmp57 = robot_ax_ang(0, 0) * robot_ax_ang(2, 0);
  const Scalar _tmp58 = _tmp50 * _tmp57;
  const Scalar _tmp59 = 2 * _tmp58;
  const Scalar _tmp60 = _tmp55 * robot_ax_ang(1, 0);
  const Scalar _tmp61 = _tmp0 * _tmp49;
  const Scalar _tmp62 = _tmp48 * _tmp61;
  const Scalar _tmp63 = -2 * _tmp62;
  const Scalar _tmp64 = _tmp2 * _tmp50;
  const Scalar _tmp65 = 1 - 2 * _tmp64;
  const Scalar _tmp66 = _extrinsics[4] * (_tmp63 + _tmp65) +
                        _extrinsics[5] * (_tmp53 - _tmp56) +
                        _extrinsics[6] * (_tmp59 + _tmp60) + robot_transl(0, 0);
  const Scalar _tmp67 = _tmp51 * robot_ax_ang(2, 0);
  const Scalar _tmp68 = 2 * _tmp67;
  const Scalar _tmp69 = _tmp55 * robot_ax_ang(0, 0);
  const Scalar _tmp70 = _tmp1 * _tmp50;
  const Scalar _tmp71 = -2 * _tmp70;
  const Scalar _tmp72 = _extrinsics[4] * (_tmp53 + _tmp56) +
                        _extrinsics[5] * (_tmp63 + _tmp71 + 1) +
                        _extrinsics[6] * (_tmp68 - _tmp69) + robot_transl(1, 0);
  const Scalar _tmp73 = _extrinsics[4] * (_tmp59 - _tmp60) +
                        _extrinsics[5] * (_tmp68 + _tmp69) +
                        _extrinsics[6] * (_tmp65 + _tmp71) + robot_transl(2, 0);
  const Scalar _tmp74 = -_tmp37 * _tmp72 + _tmp37 * landmark(1, 0) -
                        _tmp42 * _tmp73 + _tmp42 * landmark(2, 0) -
                        _tmp47 * _tmp66 + _tmp47 * landmark(0, 0);
  const Scalar _tmp75 = _tmp23 * _tmp29;
  const Scalar _tmp76 = -_tmp75;
  const Scalar _tmp77 = _tmp16 * _tmp35;
  const Scalar _tmp78 = _tmp76 + _tmp77;
  const Scalar _tmp79 = _tmp38 + _tmp41;
  const Scalar _tmp80 = 2 * std::pow(_tmp29, Scalar(2));
  const Scalar _tmp81 = -_tmp80;
  const Scalar _tmp82 = _tmp46 + _tmp81;
  const Scalar _tmp83 = -_tmp66 * _tmp79 - _tmp72 * _tmp78 - _tmp73 * _tmp82 +
                        _tmp78 * landmark(1, 0) + _tmp79 * landmark(0, 0) +
                        _tmp82 * landmark(2, 0);
  const Scalar _tmp84 = std::max<Scalar>(_tmp83, epsilon);
  const Scalar _tmp85 = Scalar(1.0) / (_tmp84);
  const Scalar _tmp86 = -_tmp24;
  const Scalar _tmp87 = _tmp36 + _tmp86;
  const Scalar _tmp88 = _tmp75 + _tmp77;
  const Scalar _tmp89 = _tmp44 + _tmp81 + 1;
  const Scalar _tmp90 = -_tmp66 * _tmp87 - _tmp72 * _tmp89 - _tmp73 * _tmp88 +
                        _tmp87 * landmark(0, 0) + _tmp88 * landmark(2, 0) +
                        _tmp89 * landmark(1, 0);
  const Scalar _tmp91 = _tmp6 / (_tmp3 * std::sqrt(_tmp3));
  const Scalar _tmp92 = _tmp1 * _tmp91;
  const Scalar _tmp93 = -_tmp19;
  const Scalar _tmp94 = (Scalar(1) / Scalar(2)) * _tmp49;
  const Scalar _tmp95 = _tmp15 * _tmp94;
  const Scalar _tmp96 = _tmp28 * _tmp94;
  const Scalar _tmp97 = _tmp57 * _tmp96;
  const Scalar _tmp98 = _tmp57 * _tmp91;
  const Scalar _tmp99 = _extrinsics[0] * _tmp98;
  const Scalar _tmp100 = _tmp21 * _tmp94;
  const Scalar _tmp101 = robot_ax_ang(0, 0) * robot_ax_ang(1, 0);
  const Scalar _tmp102 = _tmp91 * robot_ax_ang(1, 0);
  const Scalar _tmp103 = _tmp102 * robot_ax_ang(0, 0);
  const Scalar _tmp104 = -_extrinsics[3] * _tmp103 + _tmp100 * _tmp101;
  const Scalar _tmp105 = _extrinsics[2] * _tmp92 - _tmp1 * _tmp95 + _tmp104 -
                         Scalar(1) / Scalar(2) * _tmp9 + _tmp93 + _tmp97 -
                         _tmp99;
  const Scalar _tmp106 = 4 * _tmp34;
  const Scalar _tmp107 = -_tmp105 * _tmp106;
  const Scalar _tmp108 = _tmp101 * _tmp95;
  const Scalar _tmp109 = _tmp33 * _tmp94;
  const Scalar _tmp110 = _tmp109 * _tmp57;
  const Scalar _tmp111 = _extrinsics[1] * _tmp98;
  const Scalar _tmp112 = _extrinsics[2] * _tmp103;
  const Scalar _tmp113 = -_extrinsics[3] * _tmp92 + _tmp1 * _tmp100 + _tmp10 +
                         _tmp108 - _tmp110 + _tmp111 - _tmp112 -
                         Scalar(1) / Scalar(2) * _tmp18;
  const Scalar _tmp114 = 4 * _tmp29;
  const Scalar _tmp115 = -_tmp113 * _tmp114;
  const Scalar _tmp116 = _tmp107 + _tmp115;
  const Scalar _tmp117 = -_tmp12;
  const Scalar _tmp118 = _tmp101 * _tmp109;
  const Scalar _tmp119 = _extrinsics[1] * _tmp103;
  const Scalar _tmp120 = _extrinsics[2] * _tmp98 - _tmp57 * _tmp95;
  const Scalar _tmp121 = _extrinsics[0] * _tmp92 - _tmp1 * _tmp96 + _tmp117 -
                         _tmp118 + _tmp119 + _tmp120 -
                         Scalar(1) / Scalar(2) * _tmp26;
  const Scalar _tmp122 = _tmp121 * _tmp35;
  const Scalar _tmp123 = _tmp105 * _tmp23;
  const Scalar _tmp124 = _extrinsics[0] * _tmp103 - _tmp101 * _tmp96;
  const Scalar _tmp125 = -_extrinsics[3] * _tmp98 + _tmp100 * _tmp57;
  const Scalar _tmp126 = -_extrinsics[1] * _tmp92 + _tmp1 * _tmp109 + _tmp124 +
                         _tmp125 - Scalar(1) / Scalar(2) * _tmp32 + _tmp8;
  const Scalar _tmp127 = 2 * _tmp29;
  const Scalar _tmp128 = _tmp113 * _tmp40 + _tmp126 * _tmp127;
  const Scalar _tmp129 = _tmp122 + _tmp123 + _tmp128;
  const Scalar _tmp130 = _tmp103 * _tmp54;
  const Scalar _tmp131 = std::pow(_tmp14, Scalar(2));
  const Scalar _tmp132 = _tmp131 * _tmp49;
  const Scalar _tmp133 = _tmp132 * robot_ax_ang(1, 0);
  const Scalar _tmp134 = _tmp133 * robot_ax_ang(0, 0);
  const Scalar _tmp135 = -_tmp130 + _tmp134 - _tmp52;
  const Scalar _tmp136 = _tmp50 * robot_ax_ang(2, 0);
  const Scalar _tmp137 = 2 * _tmp136;
  const Scalar _tmp138 = _tmp54 * _tmp92;
  const Scalar _tmp139 = _tmp138 * robot_ax_ang(2, 0);
  const Scalar _tmp140 = 4 * _tmp48 / std::pow(_tmp3, Scalar(2));
  const Scalar _tmp141 = _tmp140 * robot_ax_ang(2, 0);
  const Scalar _tmp142 = _tmp1 * _tmp141;
  const Scalar _tmp143 = _tmp137 + _tmp139 - _tmp142;
  const Scalar _tmp144 = _tmp138 * robot_ax_ang(1, 0);
  const Scalar _tmp145 = _tmp140 * robot_ax_ang(1, 0);
  const Scalar _tmp146 = _tmp1 * _tmp145;
  const Scalar _tmp147 = 2 * _tmp51;
  const Scalar _tmp148 = _tmp144 - _tmp146 + _tmp147;
  const Scalar _tmp149 = _tmp54 * _tmp91;
  const Scalar _tmp150 = _tmp149 * _tmp57;
  const Scalar _tmp151 = _tmp132 * _tmp57;
  const Scalar _tmp152 = _tmp150 - _tmp151 + _tmp58;
  const Scalar _tmp153 = _tmp0 * _tmp91;
  const Scalar _tmp154 = _tmp153 * _tmp54;
  const Scalar _tmp155 = _tmp154 * robot_ax_ang(0, 0);
  const Scalar _tmp156 = _tmp0 * _tmp140;
  const Scalar _tmp157 = _tmp156 * robot_ax_ang(0, 0);
  const Scalar _tmp158 = -_tmp155 + _tmp157;
  const Scalar _tmp159 = _tmp2 * _tmp91;
  const Scalar _tmp160 = _tmp159 * _tmp54;
  const Scalar _tmp161 = _tmp160 * robot_ax_ang(0, 0);
  const Scalar _tmp162 = _tmp140 * _tmp2 * robot_ax_ang(0, 0);
  const Scalar _tmp163 = -_tmp161 + _tmp162;
  const Scalar _tmp164 = _extrinsics[4] * (_tmp158 + _tmp163) +
                         _extrinsics[5] * (_tmp148 + _tmp152) +
                         _extrinsics[6] * (_tmp135 + _tmp143);
  const Scalar _tmp165 = [&]() {
    const Scalar base = robot_ax_ang(0, 0);
    return base * base * base;
  }();
  const Scalar _tmp166 = _tmp50 * robot_ax_ang(0, 0);
  const Scalar _tmp167 = _tmp140 * _tmp165 - _tmp149 * _tmp165 - 4 * _tmp166;
  const Scalar _tmp168 = _tmp130 - _tmp134 + _tmp52;
  const Scalar _tmp169 = _tmp1 * _tmp132;
  const Scalar _tmp170 = _tmp102 * _tmp54 * _tmp57 - _tmp145 * _tmp57;
  const Scalar _tmp171 = _tmp170 + _tmp55;
  const Scalar _tmp172 =
      _extrinsics[4] * (_tmp143 + _tmp168) +
      _extrinsics[5] * (-_tmp138 + _tmp169 + _tmp171 - _tmp70) +
      _extrinsics[6] * (_tmp163 + _tmp167);
  const Scalar _tmp173 = _tmp113 * _tmp23;
  const Scalar _tmp174 = _tmp121 * _tmp127;
  const Scalar _tmp175 = _tmp105 * _tmp40 + _tmp126 * _tmp35;
  const Scalar _tmp176 = -_tmp173 - _tmp174 + _tmp175;
  const Scalar _tmp177 = -_tmp150 + _tmp151 - _tmp58;
  const Scalar _tmp178 = _tmp170 - _tmp55;
  const Scalar _tmp179 =
      _extrinsics[4] * (_tmp148 + _tmp177) +
      _extrinsics[5] * (_tmp158 + _tmp167) +
      _extrinsics[6] * (_tmp138 - _tmp169 + _tmp178 + _tmp70);
  const Scalar _tmp180 =
      -_tmp116 * _tmp73 + _tmp116 * landmark(2, 0) - _tmp129 * _tmp66 +
      _tmp129 * landmark(0, 0) - _tmp164 * _tmp79 - _tmp172 * _tmp82 -
      _tmp176 * _tmp72 + _tmp176 * landmark(1, 0) - _tmp179 * _tmp78;
  const Scalar _tmp181 =
      (Scalar(1) / Scalar(2)) *
      ((((_tmp83 - epsilon) > 0) - ((_tmp83 - epsilon) < 0)) + 1) /
      std::pow(_tmp84, Scalar(2));
  const Scalar _tmp182 = _tmp181 * _tmp74;
  const Scalar _tmp183 = _tmp121 * _tmp40;
  const Scalar _tmp184 = _tmp126 * _tmp23;
  const Scalar _tmp185 = _tmp105 * _tmp127 + _tmp113 * _tmp35;
  const Scalar _tmp186 = _tmp183 + _tmp184 + _tmp185;
  const Scalar _tmp187 = -_tmp122 - _tmp123 + _tmp128;
  const Scalar _tmp188 = 4 * _tmp16;
  const Scalar _tmp189 = -_tmp126 * _tmp188;
  const Scalar _tmp190 = _tmp107 + _tmp189;
  const Scalar _tmp191 = _tmp181 * _tmp90;
  const Scalar _tmp192 = -_tmp183 - _tmp184 + _tmp185;
  const Scalar _tmp193 = _tmp115 + _tmp189;
  const Scalar _tmp194 = _tmp173 + _tmp174 + _tmp175;
  const Scalar _tmp195 = _tmp154 * robot_ax_ang(1, 0);
  const Scalar _tmp196 = _tmp156 * robot_ax_ang(1, 0);
  const Scalar _tmp197 = -_tmp195 + _tmp196;
  const Scalar _tmp198 = [&]() {
    const Scalar base = robot_ax_ang(1, 0);
    return base * base * base;
  }();
  const Scalar _tmp199 = _tmp140 * _tmp198 - _tmp149 * _tmp198 - 4 * _tmp51;
  const Scalar _tmp200 = 2 * _tmp166;
  const Scalar _tmp201 = _tmp161 - _tmp162 + _tmp200;
  const Scalar _tmp202 = _tmp102 * robot_ax_ang(2, 0);
  const Scalar _tmp203 = _tmp202 * _tmp54;
  const Scalar _tmp204 = _tmp133 * robot_ax_ang(2, 0);
  const Scalar _tmp205 = _tmp203 - _tmp204 + _tmp67;
  const Scalar _tmp206 = _tmp132 * _tmp2;
  const Scalar _tmp207 =
      _extrinsics[4] * (_tmp197 + _tmp199) +
      _extrinsics[5] * (_tmp201 + _tmp205) +
      _extrinsics[6] * (-_tmp160 + _tmp171 + _tmp206 - _tmp64);
  const Scalar _tmp208 = robot_ax_ang(1, 0) * robot_ax_ang(2, 0);
  const Scalar _tmp209 = -_extrinsics[3] * _tmp202 + _tmp100 * _tmp208;
  const Scalar _tmp210 = _extrinsics[0] * _tmp159 + _tmp117 + _tmp118 -
                         _tmp119 - _tmp2 * _tmp96 + _tmp209 -
                         Scalar(1) / Scalar(2) * _tmp27;
  const Scalar _tmp211 = -_tmp188 * _tmp210;
  const Scalar _tmp212 = _tmp208 * _tmp96;
  const Scalar _tmp213 = _extrinsics[0] * _tmp202;
  const Scalar _tmp214 = -_extrinsics[3] * _tmp159 + _tmp10 + _tmp100 * _tmp2 -
                         _tmp108 + _tmp112 - Scalar(1) / Scalar(2) * _tmp17 +
                         _tmp212 - _tmp213;
  const Scalar _tmp215 = -_tmp106 * _tmp214;
  const Scalar _tmp216 = _tmp211 + _tmp215;
  const Scalar _tmp217 = _tmp160 * robot_ax_ang(2, 0);
  const Scalar _tmp218 = _tmp141 * _tmp2;
  const Scalar _tmp219 = _tmp137 + _tmp217 - _tmp218;
  const Scalar _tmp220 = -_tmp203 + _tmp204 - _tmp67;
  const Scalar _tmp221 = -_tmp144 + _tmp146;
  const Scalar _tmp222 = _extrinsics[4] * (_tmp201 + _tmp220) +
                         _extrinsics[5] * (_tmp197 + _tmp221) +
                         _extrinsics[6] * (_tmp168 + _tmp219);
  const Scalar _tmp223 = _tmp214 * _tmp23;
  const Scalar _tmp224 = -_tmp8;
  const Scalar _tmp225 = _tmp208 * _tmp95;
  const Scalar _tmp226 = _extrinsics[2] * _tmp202;
  const Scalar _tmp227 = _extrinsics[1] * _tmp159 - _tmp109 * _tmp2 + _tmp124 +
                         _tmp224 - _tmp225 + _tmp226 -
                         Scalar(1) / Scalar(2) * _tmp30;
  const Scalar _tmp228 = _tmp227 * _tmp35;
  const Scalar _tmp229 = _extrinsics[1] * _tmp202 - _tmp109 * _tmp208;
  const Scalar _tmp230 = -_extrinsics[2] * _tmp159 + _tmp104 -
                         Scalar(1) / Scalar(2) * _tmp13 + _tmp19 +
                         _tmp2 * _tmp95 + _tmp229;
  const Scalar _tmp231 = 2 * _tmp230;
  const Scalar _tmp232 = _tmp127 * _tmp210 + _tmp16 * _tmp231;
  const Scalar _tmp233 = -_tmp223 - _tmp228 + _tmp232;
  const Scalar _tmp234 =
      _extrinsics[4] * (_tmp160 + _tmp178 - _tmp206 + _tmp64) +
      _extrinsics[5] * (_tmp135 + _tmp219) +
      _extrinsics[6] * (_tmp199 + _tmp221);
  const Scalar _tmp235 = _tmp210 * _tmp23;
  const Scalar _tmp236 = _tmp227 * _tmp40;
  const Scalar _tmp237 = _tmp127 * _tmp214 + _tmp230 * _tmp35;
  const Scalar _tmp238 = _tmp235 + _tmp236 + _tmp237;
  const Scalar _tmp239 = -_tmp114 * _tmp230;
  const Scalar _tmp240 = _tmp215 + _tmp239;
  const Scalar _tmp241 = _tmp22 * _tmp231;
  const Scalar _tmp242 = _tmp127 * _tmp227;
  const Scalar _tmp243 = _tmp210 * _tmp35 + _tmp214 * _tmp40;
  const Scalar _tmp244 = -_tmp241 - _tmp242 + _tmp243;
  const Scalar _tmp245 = _tmp223 + _tmp228 + _tmp232;
  const Scalar _tmp246 =
      _tmp181 *
      (-_tmp207 * _tmp79 - _tmp222 * _tmp78 - _tmp234 * _tmp82 -
       _tmp240 * _tmp73 + _tmp240 * landmark(2, 0) - _tmp244 * _tmp72 +
       _tmp244 * landmark(1, 0) - _tmp245 * _tmp66 + _tmp245 * landmark(0, 0));
  const Scalar _tmp247 = _tmp211 + _tmp239;
  const Scalar _tmp248 = _tmp241 + _tmp242 + _tmp243;
  const Scalar _tmp249 = -_tmp235 - _tmp236 + _tmp237;
  const Scalar _tmp250 = (Scalar(1) / Scalar(2)) * _tmp61;
  const Scalar _tmp251 = -_extrinsics[0] * _tmp153 + _tmp12 + _tmp120 +
                         _tmp209 - Scalar(1) / Scalar(2) * _tmp25 +
                         _tmp250 * _tmp28;
  const Scalar _tmp252 = -_tmp106 * _tmp251;
  const Scalar _tmp253 = -_extrinsics[3] * _tmp153 + _tmp10 + _tmp110 -
                         _tmp111 - Scalar(1) / Scalar(2) * _tmp20 +
                         _tmp21 * _tmp250 - _tmp212 + _tmp213;
  const Scalar _tmp254 = -_tmp188 * _tmp253;
  const Scalar _tmp255 = _tmp252 + _tmp254;
  const Scalar _tmp256 = _tmp23 * _tmp251;
  const Scalar _tmp257 = _extrinsics[2] * _tmp153 -
                         Scalar(1) / Scalar(2) * _tmp11 - _tmp15 * _tmp250 +
                         _tmp229 + _tmp93 - _tmp97 + _tmp99;
  const Scalar _tmp258 = _tmp257 * _tmp35;
  const Scalar _tmp259 = _extrinsics[1] * _tmp153 + _tmp125 + _tmp224 +
                         _tmp225 - _tmp226 - _tmp250 * _tmp33 -
                         Scalar(1) / Scalar(2) * _tmp31;
  const Scalar _tmp260 = _tmp127 * _tmp253 + _tmp259 * _tmp40;
  const Scalar _tmp261 = -_tmp256 - _tmp258 + _tmp260;
  const Scalar _tmp262 = -_tmp217 + _tmp218;
  const Scalar _tmp263 = [&]() {
    const Scalar base = robot_ax_ang(2, 0);
    return base * base * base;
  }();
  const Scalar _tmp264 = -4 * _tmp136 + _tmp140 * _tmp263 - _tmp149 * _tmp263;
  const Scalar _tmp265 = _tmp155 - _tmp157 + _tmp200;
  const Scalar _tmp266 = _tmp131 * _tmp61;
  const Scalar _tmp267 =
      _extrinsics[4] * (_tmp262 + _tmp264) +
      _extrinsics[5] * (_tmp154 + _tmp178 - _tmp266 + _tmp62) +
      _extrinsics[6] * (_tmp220 + _tmp265);
  const Scalar _tmp268 = -_tmp139 + _tmp142;
  const Scalar _tmp269 = _tmp147 + _tmp195 - _tmp196;
  const Scalar _tmp270 =
      _extrinsics[4] * (-_tmp154 + _tmp171 + _tmp266 - _tmp62) +
      _extrinsics[5] * (_tmp264 + _tmp268) +
      _extrinsics[6] * (_tmp152 + _tmp269);
  const Scalar _tmp271 = _extrinsics[4] * (_tmp205 + _tmp265) +
                         _extrinsics[5] * (_tmp177 + _tmp269) +
                         _extrinsics[6] * (_tmp262 + _tmp268);
  const Scalar _tmp272 = _tmp257 * _tmp40;
  const Scalar _tmp273 = _tmp23 * _tmp253;
  const Scalar _tmp274 = _tmp127 * _tmp251 + _tmp259 * _tmp35;
  const Scalar _tmp275 = _tmp272 + _tmp273 + _tmp274;
  const Scalar _tmp276 = _tmp256 + _tmp258 + _tmp260;
  const Scalar _tmp277 = _tmp127 * _tmp257;
  const Scalar _tmp278 = _tmp23 * _tmp259;
  const Scalar _tmp279 = _tmp251 * _tmp40 + _tmp253 * _tmp35;
  const Scalar _tmp280 = -_tmp277 - _tmp278 + _tmp279;
  const Scalar _tmp281 = -_tmp114 * _tmp259;
  const Scalar _tmp282 = _tmp252 + _tmp281;
  const Scalar _tmp283 =
      -_tmp267 * _tmp79 - _tmp270 * _tmp78 - _tmp271 * _tmp82 -
      _tmp276 * _tmp66 + _tmp276 * landmark(0, 0) - _tmp280 * _tmp72 +
      _tmp280 * landmark(1, 0) - _tmp282 * _tmp73 + _tmp282 * landmark(2, 0);
  const Scalar _tmp284 = _tmp277 + _tmp278 + _tmp279;
  const Scalar _tmp285 = _tmp254 + _tmp281;
  const Scalar _tmp286 = -_tmp272 - _tmp273 + _tmp274;
  const Scalar _tmp287 = _tmp45 - 1;
  const Scalar _tmp288 = -_tmp41;
  const Scalar _tmp289 = _tmp288 + _tmp39;
  const Scalar _tmp290 = -_tmp36;
  const Scalar _tmp291 = -_tmp77;
  const Scalar _tmp292 = _tmp291 + _tmp75;
  const Scalar _tmp293 = _tmp287 + _tmp80;

  // Output terms (4)
  Eigen::Matrix<Scalar, 2, 1> _res;

  _res(0, 0) = pixel_err_mult_x * (_tmp74 * _tmp85 - obs(0, 0));
  _res(1, 0) = pixel_err_mult_y * (_tmp85 * _tmp90 - obs(1, 0));

  if (res_D_robot_ax_ang != nullptr) {
    Eigen::Matrix<Scalar, 2, 3>& _res_D_robot_ax_ang = (*res_D_robot_ax_ang);

    _res_D_robot_ax_ang(0, 0) =
        pixel_err_mult_x *
        (-_tmp180 * _tmp182 +
         _tmp85 * (-_tmp164 * _tmp47 - _tmp172 * _tmp42 - _tmp179 * _tmp37 -
                   _tmp186 * _tmp72 + _tmp186 * landmark(1, 0) -
                   _tmp187 * _tmp73 + _tmp187 * landmark(2, 0) -
                   _tmp190 * _tmp66 + _tmp190 * landmark(0, 0)));
    _res_D_robot_ax_ang(1, 0) =
        pixel_err_mult_y *
        (-_tmp180 * _tmp191 +
         _tmp85 * (-_tmp164 * _tmp87 - _tmp172 * _tmp88 - _tmp179 * _tmp89 -
                   _tmp192 * _tmp66 + _tmp192 * landmark(0, 0) -
                   _tmp193 * _tmp72 + _tmp193 * landmark(1, 0) -
                   _tmp194 * _tmp73 + _tmp194 * landmark(2, 0)));
    _res_D_robot_ax_ang(0, 1) =
        pixel_err_mult_x *
        (-_tmp246 * _tmp74 +
         _tmp85 *
             (-_tmp207 * _tmp47 - _tmp216 * _tmp66 + _tmp216 * landmark(0, 0) -
              _tmp222 * _tmp37 - _tmp233 * _tmp73 + _tmp233 * landmark(2, 0) -
              _tmp234 * _tmp42 - _tmp238 * _tmp72 + _tmp238 * landmark(1, 0)));
    _res_D_robot_ax_ang(1, 1) =
        pixel_err_mult_y *
        (-_tmp246 * _tmp90 +
         _tmp85 * (-_tmp207 * _tmp87 - _tmp222 * _tmp89 - _tmp234 * _tmp88 -
                   _tmp247 * _tmp72 + _tmp247 * landmark(1, 0) -
                   _tmp248 * _tmp73 + _tmp248 * landmark(2, 0) -
                   _tmp249 * _tmp66 + _tmp249 * landmark(0, 0)));
    _res_D_robot_ax_ang(0, 2) =
        pixel_err_mult_x *
        (-_tmp182 * _tmp283 +
         _tmp85 *
             (-_tmp255 * _tmp66 + _tmp255 * landmark(0, 0) - _tmp261 * _tmp73 +
              _tmp261 * landmark(2, 0) - _tmp267 * _tmp47 - _tmp270 * _tmp37 -
              _tmp271 * _tmp42 - _tmp275 * _tmp72 + _tmp275 * landmark(1, 0)));
    _res_D_robot_ax_ang(1, 2) =
        pixel_err_mult_y *
        (-_tmp191 * _tmp283 +
         _tmp85 * (-_tmp267 * _tmp87 - _tmp270 * _tmp89 - _tmp271 * _tmp88 -
                   _tmp284 * _tmp73 + _tmp284 * landmark(2, 0) -
                   _tmp285 * _tmp72 + _tmp285 * landmark(1, 0) -
                   _tmp286 * _tmp66 + _tmp286 * landmark(0, 0)));
  }

  if (res_D_robot_transl != nullptr) {
    Eigen::Matrix<Scalar, 2, 3>& _res_D_robot_transl = (*res_D_robot_transl);

    _res_D_robot_transl(0, 0) =
        pixel_err_mult_x * (-_tmp182 * _tmp289 + _tmp85 * (_tmp287 + _tmp43));
    _res_D_robot_transl(1, 0) =
        pixel_err_mult_y * (-_tmp191 * _tmp289 + _tmp85 * (_tmp24 + _tmp290));
    _res_D_robot_transl(0, 1) =
        pixel_err_mult_x * (-_tmp182 * _tmp292 + _tmp85 * (_tmp290 + _tmp86));
    _res_D_robot_transl(1, 1) =
        pixel_err_mult_y *
        (-_tmp191 * _tmp292 + _tmp85 * (_tmp43 + _tmp80 - 1));
    _res_D_robot_transl(0, 2) =
        pixel_err_mult_x * (-_tmp182 * _tmp293 + _tmp85 * (_tmp288 + _tmp38));
    _res_D_robot_transl(1, 2) =
        pixel_err_mult_y * (-_tmp191 * _tmp293 + _tmp85 * (_tmp291 + _tmp76));
  }

  if (res_D_landmark != nullptr) {
    Eigen::Matrix<Scalar, 2, 3>& _res_D_landmark = (*res_D_landmark);

    _res_D_landmark(0, 0) =
        pixel_err_mult_x * (-_tmp182 * _tmp79 + _tmp47 * _tmp85);
    _res_D_landmark(1, 0) =
        pixel_err_mult_y * (-_tmp191 * _tmp79 + _tmp85 * _tmp87);
    _res_D_landmark(0, 1) =
        pixel_err_mult_x * (-_tmp182 * _tmp78 + _tmp37 * _tmp85);
    _res_D_landmark(1, 1) =
        pixel_err_mult_y * (-_tmp191 * _tmp78 + _tmp85 * _tmp89);
    _res_D_landmark(0, 2) =
        pixel_err_mult_x * (-_tmp182 * _tmp82 + _tmp42 * _tmp85);
    _res_D_landmark(1, 2) =
        pixel_err_mult_y * (-_tmp191 * _tmp82 + _tmp85 * _tmp88);
  }

  return _res;
}  // NOLINT(readability/fn_size)

// NOLINTNEXTLINE(readability/fn_size)
}  // namespace sym
